# Generated by Django 4.2.5 on 2023-12-24 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="add",
            old_name="newusername",
            new_name="username",
        ),
    ]
