# Generated by Django 4.2.5 on 2023-12-24 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("detector", "0002_rename_newusername_add_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="add",
            new_name="User",
        ),
    ]
